    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ASUS
 */
public class FrmListadoPeliculas extends javax.swing.JFrame {

    
    //String[] nombresPeliculas = {"Los Increíbles","Titanic","Joker", "Moana","Doctor Strange","Batman", "Mufasa","Avengers: Endgame", "El tiempo que tenemos", "Sonic 3","Hasta el ultimo hombre" ,"Spiderman" };
    DefaultTableModel model = new DefaultTableModel(new Object[]{"Imagen", "Nombre"}, 0);
    private JLabel labelsImagenes[]= new JLabel[12];
    
    Icon imagen1= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Los increibles.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen2= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Titanic.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen3= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Joker.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen4= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Moana.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen5= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Doctor Strange.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen6= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Batman.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen7= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Mufasa.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen8= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Los Vengadores.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen9= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/El tiempo que tenemos.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen10= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Sonic 3.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen11= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Hasta el ultimo hombre.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen12= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Spiderman.jpg")).getImage().getScaledInstance(70,100,0));
    
    
    public FrmListadoPeliculas() {
        initComponents();
        
    }
    
    public FrmListadoPeliculas(String[] nombresPeliculas) {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        labelsImagenes[0]=new JLabel(imagen1);
        labelsImagenes[1]=new JLabel(imagen2);
        labelsImagenes[2]=new JLabel(imagen3);
        labelsImagenes[3]=new JLabel(imagen4);
        labelsImagenes[4]=new JLabel(imagen5);
        labelsImagenes[5]=new JLabel(imagen6);
        labelsImagenes[6]=new JLabel(imagen7);
        labelsImagenes[7]=new JLabel(imagen8);
        labelsImagenes[8]=new JLabel(imagen9);
        labelsImagenes[9]=new JLabel(imagen10);
        labelsImagenes[10]=new JLabel(imagen11);
        labelsImagenes[11]=new JLabel(imagen12);
        
        jTable1.setModel(model);
        estilizarTabla(jTable1,  model);
        configurarTabla(jTable1, nombresPeliculas, labelsImagenes);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Listado de películas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(194, 194, 194))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListadoPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListadoPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListadoPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListadoPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListadoPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
    
     public static void configurarTabla(JTable tabla, String[] nombresPeliculas, JLabel[] labelsImagenes) {
        // Crear el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Imagen", "Nombre"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 0 ? JLabel.class : String.class;
            }
        };
        tabla.setModel(modelo);
        tabla.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                                                            boolean hasFocus, int row, int column) {
                if (value instanceof JLabel) {
                    JLabel label = (JLabel) value;
                    label.setOpaque(true);
                    label.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                    label.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
                    return label;
                }
                return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            }
        });
        for (String nombre : nombresPeliculas) {
            JLabel imagenLabel = obtenerImagenLabel(nombre, labelsImagenes);
            modelo.addRow(new Object[]{imagenLabel, nombre});
        }
        tabla.setRowHeight(100 + 10);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(80); 
        tabla.getColumnModel().getColumn(1).setPreferredWidth(100); 
    }

    private static JLabel obtenerImagenLabel(String nombre, JLabel[] labelsImagenes) {
        switch (nombre) {
            case "Los Increíbles":
                return labelsImagenes[0];
            case "Titanic":
                return labelsImagenes[1];
            case "Joker":
                return labelsImagenes[2];
            case "Moana":
                return labelsImagenes[3];
            case "Doctor Strange":
                return labelsImagenes[4];
            case "Batman":
                return labelsImagenes[5];
            case "Mufasa":
                return labelsImagenes[6];
            case "Avengers: Endgame":
                return labelsImagenes[7];
            case "El tiempo que tenemos":
                return labelsImagenes[8];
            case "Sonic 3":
                return labelsImagenes[9];
            case "Hasta el ultimo hombre":
                return labelsImagenes[10];
            case "Spiderman":
                return labelsImagenes[11];
            default:
                return new JLabel("Sin imagen");
        }
    }

    public static void estilizarTabla(JTable tabla, DefaultTableModel modelo) {
        // Asignar el modelo de la tabla
        tabla.setModel(modelo);

        // Configurar el color de fondo de la tabla y las filas seleccionadas
        tabla.setBackground(Color.WHITE); // Fondo blanco para la tabla
        tabla.setSelectionBackground(Color.decode("#F0F0F0")); // Color del fondo cuando se selecciona una celda
        tabla.setSelectionForeground(Color.BLACK); // Color del texto cuando se selecciona una celda

        // Configurar la altura de las filas y la fuente
        tabla.setRowHeight(30); // Establecer altura de las filas
        tabla.setFont(new Font("Arial", Font.PLAIN, 14)); // Fuente de la tabla

        // Estilo de las celdas: sin bordes visibles pero con bordes internos personalizados
        tabla.setShowGrid(false); // Desactivar la cuadrícula
        tabla.setIntercellSpacing(new Dimension(0, 0)); // Eliminar el espacio entre las celdas
        tabla.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1)); // Borde externo de la tabla

        // Estilo de las cabeceras
        JTableHeader cabecera = tabla.getTableHeader();
        cabecera.setBackground(Color.LIGHT_GRAY); // Fondo gris claro para la cabecera
        cabecera.setFont(new Font("Arial", Font.BOLD, 14)); // Fuente negrita en la cabecera
        cabecera.setPreferredSize(new Dimension(100, 40)); // Ajuste del tamaño de la cabecera

        // Configuración del borde interno de las celdas
        DefaultTableCellRenderer render = new DefaultTableCellRenderer();
        render.setBorder(BorderFactory.createMatteBorder(0, 1, 1, 1, Color.decode("#CCCCCC"))); // Bordes internos sutiles
        tabla.setDefaultRenderer(Object.class, render);
    }


}
