/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ASUS
 */
public class FrmListadoProductos extends javax.swing.JFrame {

    
    
    DefaultTableModel model = new DefaultTableModel(new Object[]{"Imagen", "Nombre","Precio"}, 0);
    private JLabel labelsImagenes[]= new JLabel[12];
    
    //BEBIDAS
    Icon imagen1= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/bebida1.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen2= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/bebida2.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen3= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/bebida3.jpg")).getImage().getScaledInstance(70,100,0));
    //COMBOS
    Icon imagen4= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Combo1.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen5= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Combo2.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen6= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Combo3.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen7= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Combo4.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen8= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Combo5.jpg")).getImage().getScaledInstance(70,100,0));
    Icon imagen9= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/Combo6.jpg")).getImage().getScaledInstance(70,100,0));
    
    
    
    public FrmListadoProductos() {
        initComponents();
        
    }
    
    public FrmListadoProductos(String[] nombresProductos) {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        labelsImagenes[0]=new JLabel(imagen1);
        labelsImagenes[1]=new JLabel(imagen2);
        labelsImagenes[2]=new JLabel(imagen3);
        labelsImagenes[3]=new JLabel(imagen4);
        labelsImagenes[4]=new JLabel(imagen5);
        labelsImagenes[5]=new JLabel(imagen6);
        labelsImagenes[6]=new JLabel(imagen7);
        labelsImagenes[7]=new JLabel(imagen8);
        labelsImagenes[8]=new JLabel(imagen9);
        
        jTable1.setModel(model);
        estilizarTabla(jTable1,  model);
        configurarTabla(jTable1, nombresProductos, labelsImagenes);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Listado de productos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListadoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListadoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListadoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListadoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListadoProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
    
     public static void configurarTabla(JTable tabla, String[] nombresProductos, JLabel[] labelsImagenes) {
        // Crear el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Imagen", "Nombre","Precio"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 0 ? JLabel.class : String.class;
            }
        };
        tabla.setModel(modelo);
        tabla.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                                                            boolean hasFocus, int row, int column) {
                if (value instanceof JLabel) {
                    JLabel label = (JLabel) value;
                    label.setOpaque(true);
                    label.setBackground(isSelected ? table.getSelectionBackground() : table.getBackground());
                    label.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
                    return label;
                }
                return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            }
        });
        for (String nombre : nombresProductos) {
            JLabel imagenLabel = obtenerImagenLabel(nombre, labelsImagenes);
            double numero=obtenerPrecio(nombre);
            modelo.addRow(new Object[]{imagenLabel, nombre,numero});
        }
        tabla.setRowHeight(100 + 10);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(80); 
        tabla.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(50);
    }

    private static JLabel obtenerImagenLabel(String nombre, JLabel[] labelsImagenes) {
        switch (nombre) {
            case "CCBebida Mediana OL ":
                return labelsImagenes[0];
            case "CCBebida Grande OL ":
                return labelsImagenes[1];
            case "Agua San Luis sin gas ":
                return labelsImagenes[2];
            case "Combo 2 Dulce OL CC ":
                return labelsImagenes[3];
            case "Combo 2 Salado OL CC ":
                return labelsImagenes[4];
            case "Combo 2 Mix OL CC ":
                return labelsImagenes[5];
            case "Com.2 Salado Dob.Gig. OL ":
                return labelsImagenes[6];
            case "Com.2 Mix Dob.Gig. OL ":
                return labelsImagenes[7];
            case "Com.2 Dulce Dob.Gig. OL ":
                return labelsImagenes[8];
            default:
                return new JLabel("Sin imagen");
        }
    }
    private static double obtenerPrecio(String nombre){
        switch (nombre) {
            case "CCBebida Mediana OL ":
                return 13;
            case "CCBebida Grande OL ":
                return 15;
            case "Agua San Luis sin gas ":
                return 5;
            case "Combo 2 Dulce OL CC ":
                return 23;
            case "Combo 2 Salado OL CC ":
                return 26.50;
            case "Combo 2 Mix OL CC ":
                return 29;
            case "Com.2 Salado Dob.Gig. OL ":
                return 43;
            case "Com.2 Mix Dob.Gig. OL ":
                return 39;
            case "Com.2 Dulce Dob.Gig. OL ":
                return 43;
            default:
                return -1;
        }
    }

    public static void estilizarTabla(JTable tabla, DefaultTableModel modelo) {
        tabla.setModel(modelo);
        tabla.setBackground(Color.WHITE); 
        tabla.setSelectionBackground(Color.decode("#F0F0F0"));
        tabla.setSelectionForeground(Color.BLACK);
        tabla.setRowHeight(30); 
        tabla.setFont(new Font("Arial", Font.PLAIN, 14)); 
        tabla.setShowGrid(false); // Desactivar la cuadrícula
        tabla.setIntercellSpacing(new Dimension(0, 0)); // Eliminar el espacio entre las celdas
        tabla.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1)); // Borde externo de la tabla

        // Estilo de las cabeceras
        JTableHeader cabecera = tabla.getTableHeader();
        cabecera.setBackground(Color.LIGHT_GRAY); // Fondo gris claro para la cabecera
        cabecera.setFont(new Font("Arial", Font.BOLD, 14)); // Fuente negrita en la cabecera
        cabecera.setPreferredSize(new Dimension(100, 40)); // Ajuste del tamaño de la cabecera

        // Configuración del borde interno de las celdas
        DefaultTableCellRenderer render = new DefaultTableCellRenderer();
        render.setBorder(BorderFactory.createMatteBorder(0, 1, 1, 1, Color.decode("#CCCCCC"))); // Bordes internos sutiles
        tabla.setDefaultRenderer(Object.class, render);
    }


}
