package presentacion;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class FrmPeliculas extends javax.swing.JFrame {

    private int idCliente;
    public FrmPeliculas(int idCliente) {
        this.idCliente = idCliente;
        initComponents();
        mostrarPanel(new PanelCartelera(idCliente));
        SetImageLabel(lblFiltrar, "src/imagenes/filtrar.png");
        cbxGenero.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        //idioma
        cbxIdioma.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformedIdioma(evt);
            }
        });
        //censura
        cbxCensura.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformedCensura(evt);
            }
        });
        jPanel2.setLayout(new BorderLayout()); 
    }
    
    public FrmPeliculas() {
        initComponents();
        mostrarPanel(new PanelCartelera());
        SetImageLabel(lblFiltrar, "src/imagenes/filtrar.png");
        cbxGenero.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        //idioma
        cbxIdioma.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformedIdioma(evt);
            }
        });
        //censura
        cbxCensura.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformedCensura(evt);
            }
        });
        jPanel2.setLayout(new BorderLayout()); 
    }

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtener el género seleccionado
        String seleccionado = (String) cbxGenero.getSelectedItem();

        // Mostrar el panel correspondiente según la selección
        if (seleccionado.equals("Accion")) {
            mostrarPanel(new PanelAccion());  // Mostrar PanelAccion
        } else if (seleccionado.equals("Animacion")) {
            mostrarPanel(new PanelAnimacion());  // Mostrar PanelAnimacion
        } else if (seleccionado.equals("Drama")) {
            mostrarPanel(new PanelDrama());  // Mostrar PanelDrama
        }
    }

    // Idioma 
    private void comboBoxActionPerformedIdioma(java.awt.event.ActionEvent evt) {
        // Obtener el género seleccionado
        String seleccionado = (String) cbxIdioma.getSelectedItem();

        // Mostrar el panel correspondiente según la selección
        if (seleccionado.equals("Español")) {
            mostrarPanel(new PanelEspañol());  // Mostrar PanelAccion
        } else if (seleccionado.equals("Ingles")) {
            mostrarPanel(new PanelIngles());  // Mostrar PanelAnimacion
        }
    }
    //censura
    private void comboBoxActionPerformedCensura(java.awt.event.ActionEvent evt) {
        // Obtener el género seleccionado
        String seleccionado = (String) cbxCensura.getSelectedItem();

        // Mostrar el panel correspondiente según la selección
        if (seleccionado.equals("+18")) {
            mostrarPanel(new PanelMAS18());  // Mostrar PanelAccion
        } else if (seleccionado.equals("+14")) {
            mostrarPanel(new PanelMAS14());  // Mostrar PanelAnimacion
        } else if (seleccionado.equals("APT")) {
            mostrarPanel(new PanelAPT());  // Mostrar PanelAnimacion
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPeliculas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rdbtnCartelera = new javax.swing.JRadioButton();
        rdbtnProximosEstrenos = new javax.swing.JRadioButton();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        lblFiltrar = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        cbxIdioma = new javax.swing.JComboBox<>();
        cbxCensura = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Peliculas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Square721 BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Películas");

        btgPeliculas.add(rdbtnCartelera);
        rdbtnCartelera.setFont(new java.awt.Font("Square721 BT", 1, 16)); // NOI18N
        rdbtnCartelera.setForeground(new java.awt.Color(0, 51, 153));
        rdbtnCartelera.setSelected(true);
        rdbtnCartelera.setText("En cartelera");
        rdbtnCartelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbtnCarteleraMouseClicked(evt);
            }
        });
        rdbtnCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnCarteleraActionPerformed(evt);
            }
        });

        btgPeliculas.add(rdbtnProximosEstrenos);
        rdbtnProximosEstrenos.setFont(new java.awt.Font("Square721 BT", 1, 16)); // NOI18N
        rdbtnProximosEstrenos.setForeground(new java.awt.Color(0, 51, 153));
        rdbtnProximosEstrenos.setText("Próximos Estrenos");
        rdbtnProximosEstrenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbtnProximosEstrenosMouseClicked(evt);
            }
        });
        rdbtnProximosEstrenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnProximosEstrenosActionPerformed(evt);
            }
        });

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Filtrar por:");

        cbxGenero.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accion", "Animacion", "Drama", " " }));
        cbxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroActionPerformed(evt);
            }
        });

        cbxIdioma.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        cbxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Ingles" }));

        cbxCensura.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        cbxCensura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+14", "+18", "APT" }));

        jLabel18.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel18.setText("Género:");

        jLabel19.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel19.setText("Idioma:");

        jLabel21.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel21.setText("Censura:");

        jPanel2.setPreferredSize(new java.awt.Dimension(674, 611));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)
                                .addGap(109, 109, 109)
                                .addComponent(rdbtnCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(rdbtnProximosEstrenos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(lblFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cbxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbxCensura, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnCartelera)
                            .addComponent(rdbtnProximosEstrenos))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(cbxCensura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnCarteleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnCarteleraMouseClicked
        verificar();
    }//GEN-LAST:event_rdbtnCarteleraMouseClicked

    private void rdbtnProximosEstrenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnProximosEstrenosMouseClicked
        verificar();
    }//GEN-LAST:event_rdbtnProximosEstrenosMouseClicked

    private void rdbtnCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnCarteleraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnCarteleraActionPerformed

    private void rdbtnProximosEstrenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnProximosEstrenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnProximosEstrenosActionPerformed

    private void cbxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPeliculas().setVisible(true);
            }
        });
    }

    public void verificar() {
        boolean cartelera = false;
        boolean prox_estr = false;
        if (rdbtnCartelera.isSelected()) {
            cartelera = true;
        } else {
            prox_estr = true;
        }

        if (cartelera) {
            mostrarPanel(new PanelCartelera(idCliente));
        } else {
            mostrarPanel(new PanelProximosEstrenos(idCliente));
        }
    }

      private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT)
        );
        labelName.setIcon(icon);
        this.repaint();
    }

    public void mostrarPanel(JPanel panel) {
        panel.setSize(674, 611);  // Ajustar el tamaño del nuevo panel
        panel.setLocation(0, 0);   // Posición sobre el jPanel2
        panel.setBackground(Color.WHITE);  // Fondo blanco

        jPanel2.removeAll();  // Limpiar el contenido actual
        jPanel2.add(panel, BorderLayout.CENTER);  // Añadir el nuevo panel
        jPanel2.revalidate();  // Validar el layout
        jPanel2.repaint();     // Redibujar el panel
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgPeliculas;
    private javax.swing.JComboBox<String> cbxCensura;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JComboBox<String> cbxIdioma;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JRadioButton rdbtnCartelera;
    private javax.swing.JRadioButton rdbtnProximosEstrenos;
    // End of variables declaration//GEN-END:variables
}
