package presentacion;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;

public class PanelRegistroSocio extends javax.swing.JPanel {

    
    public PanelRegistroSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtApellidos = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtNumeroDocumento = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        panelRound5 = new redondeadoPanel.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtDepartamento = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtContraeña = new javax.swing.JTextField();
        cbxTipoDocumento = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese su nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txtApellidos.setForeground(new java.awt.Color(204, 204, 204));
        txtApellidos.setText("Ingrese sus apellidos");
        txtApellidos.setBorder(null);
        txtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidosMousePressed(evt);
            }
        });
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txtNumeroDocumento.setForeground(new java.awt.Color(204, 204, 204));
        txtNumeroDocumento.setText("Ingrese su nro de documento");
        txtNumeroDocumento.setBorder(null);
        txtNumeroDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroDocumentoMousePressed(evt);
            }
        });
        txtNumeroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDocumentoActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        panelRound5.setBackground(new java.awt.Color(0, 51, 153));
        panelRound5.setRoundBottomLeft(50);
        panelRound5.setRoundBottomRight(50);
        panelRound5.setRoundTopLeft(50);
        panelRound5.setRoundTopRight(50);
        panelRound5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRound5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRound5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound5MousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("REGISTRARSE");

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
            .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound5Layout.createSequentialGroup()
                    .addGap(0, 42, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel1.setText("Apellidos");

        jLabel2.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel5.setText("Número de documento");

        jLabel3.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel3.setText("Edad");

        txtEdad.setForeground(new java.awt.Color(204, 204, 204));
        txtEdad.setText("Ingrese su Edad");
        txtEdad.setBorder(null);
        txtEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEdadMousePressed(evt);
            }
        });
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel6.setText("Correo");

        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.setText("Ingrese su correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        txtDepartamento.setForeground(new java.awt.Color(204, 204, 204));
        txtDepartamento.setText("Ingrese su departamento");
        txtDepartamento.setBorder(null);
        txtDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDepartamentoMousePressed(evt);
            }
        });
        txtDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartamentoActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel7.setText("Departamento");

        jLabel8.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel8.setText("Contraseña");

        txtContraeña.setBorder(null);
        txtContraeña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraeñaMousePressed(evt);
            }
        });
        txtContraeña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraeñaActionPerformed(evt);
            }
        });

        cbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Carnet de extranjería", "Pasaporte", "Rut" }));
        cbxTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoDocumentoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel9.setText("Tipo de documento");

        jLabel4.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("REGISTRARSE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtContraeña))
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo)
                            .addComponent(jSeparator6)
                            .addComponent(txtApellidos)
                            .addComponent(jSeparator2)
                            .addComponent(txtNombre)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator3)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNumeroDocumento))
                                        .addGap(130, 130, 130)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7)
                                        .addComponent(txtDepartamento)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 62, Short.MAX_VALUE)))
                        .addGap(109, 109, 109))))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContraeña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        if(txtNombre.getText().equals("Ingrese su nombre")){
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if(txtApellidos.getText().equals("")){
            txtApellidos.setText("Ingrese sus apellidos");
            txtApellidos.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtEdad.getText().equals("")){
            txtEdad.setText("Ingrese su Edad");
            txtEdad.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtCorreo.getText().equals("")){
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtNumeroDocumento.getText().equals("")){
            txtNumeroDocumento.setText("Ingrese su nro de documento");
            txtNumeroDocumento.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtDepartamento.getText().equals("")){
            txtDepartamento.setText("Ingrese su departamento");
            txtDepartamento.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosMousePressed
        if(txtNombre.getText().equals("")){
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtApellidos.getText().equals("Ingrese sus apellidos")){
            txtApellidos.setText("");
            txtApellidos.setForeground(Color.black);
        }
        if(txtEdad.getText().equals("")){
            txtEdad.setText("Ingrese su Edad");
            txtEdad.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtCorreo.getText().equals("")){
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtNumeroDocumento.getText().equals("")){
            txtNumeroDocumento.setText("Ingrese su nro de documento");
            txtNumeroDocumento.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtDepartamento.getText().equals("")){
            txtDepartamento.setText("Ingrese su departamento");
            txtDepartamento.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_txtApellidosMousePressed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtNumeroDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroDocumentoMousePressed
        if(txtNombre.getText().equals("")){
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtApellidos.getText().equals("")){
            txtApellidos.setText("Ingrese sus apellidos");
            txtApellidos.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtEdad.getText().equals("")){
            txtEdad.setText("Ingrese su Edad");
            txtEdad.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtCorreo.getText().equals("")){
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtNumeroDocumento.getText().equals("Ingrese su nro de documento")){
            txtNumeroDocumento.setText("");
            txtNumeroDocumento.setForeground(Color.black);
        }
        if(txtDepartamento.getText().equals("")){
            txtDepartamento.setText("Ingrese su departamento");
            txtDepartamento.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_txtNumeroDocumentoMousePressed

    private void txtNumeroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDocumentoActionPerformed

    private void panelRound5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound5MouseEntered
        panelRound5.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        panelRound5.setBackground(Color.red);
    }//GEN-LAST:event_panelRound5MouseEntered

    private void panelRound5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound5MouseExited
        panelRound5.setBackground(new Color(0,51,153));
    }//GEN-LAST:event_panelRound5MouseExited

    private void txtEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEdadMousePressed
        if(txtNombre.getText().equals("")){
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtApellidos.getText().equals("")){
            txtApellidos.setText("Ingrese sus apellidos");
            txtApellidos.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtEdad.getText().equals("Ingrese su Edad")){
            txtEdad.setText("");
            txtEdad.setForeground(Color.black);
        }
        if(txtCorreo.getText().equals("")){
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtNumeroDocumento.getText().equals("")){
            txtNumeroDocumento.setText("Ingrese su nro de documento");
            txtNumeroDocumento.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtDepartamento.getText().equals("")){
            txtDepartamento.setText("Ingrese su departamento");
            txtDepartamento.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_txtEdadMousePressed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        if(txtNombre.getText().equals("")){
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtApellidos.getText().equals("")){
            txtApellidos.setText("Ingrese sus apellidos");
            txtApellidos.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtEdad.getText().equals("")){
            txtEdad.setText("Ingrese su Edad");
            txtEdad.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtCorreo.getText().equals("Ingrese su correo")){
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
        if(txtNumeroDocumento.getText().equals("")){
            txtNumeroDocumento.setText("Ingrese su nro de documento");
            txtNumeroDocumento.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtDepartamento.getText().equals("")){
            txtDepartamento.setText("Ingrese su departamento");
            txtDepartamento.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void panelRound5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound5MousePressed
        if(txtNombre.getText().equals("")||txtApellidos.getText().equals("")||txtNumeroDocumento.getText().equals("")||txtEdad.getText().equals("")||txtCorreo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Rellene todos los espacios");
        }else{
            //LOGICA
        }
    }//GEN-LAST:event_panelRound5MousePressed

    private void txtDepartamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDepartamentoMousePressed
        if(txtNombre.getText().equals("")){
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtApellidos.getText().equals("")){
            txtApellidos.setText("Ingrese sus apellidos");
            txtApellidos.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtEdad.getText().equals("")){
            txtEdad.setText("Ingrese su Edad");
            txtEdad.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtCorreo.getText().equals("")){
            txtCorreo.setText("Ingrese su correo");
            txtCorreo.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtNumeroDocumento.getText().equals("")){
            txtNumeroDocumento.setText("Ingrese su nro de documento");
            txtNumeroDocumento.setForeground(Color.decode("#CCCCCC"));
        }
        if(txtDepartamento.getText().equals("Ingrese su departamento")){
            txtDepartamento.setText("");
            txtDepartamento.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtDepartamentoMousePressed

    private void txtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentoActionPerformed

    private void txtContraeñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraeñaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraeñaMousePressed

    private void txtContraeñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraeñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraeñaActionPerformed

    private void cbxTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoDocumentoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void panelRound5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound5MouseClicked
         // Obtener los valores de los campos de texto
    String nombre = txtNombre.getText();
    String apellidos = txtApellidos.getText();
    String correo = txtCorreo.getText();
    String contraseña = txtContraeña.getText();
    String departamento = txtDepartamento.getText();
    String numeroDocumento = txtNumeroDocumento.getText();
    String tipoDocumento = cbxTipoDocumento.getSelectedItem().toString();
    int edad;

    // Validar y convertir la edad
    try {
        edad = Integer.parseInt(txtEdad.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La edad debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar que no haya campos vacíos
    if (nombre.isEmpty() || apellidos.isEmpty() || correo.isEmpty() || contraseña.isEmpty() || 
        departamento.isEmpty() || numeroDocumento.isEmpty() || tipoDocumento.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Insertar en la base de datos
    String query = "INSERT INTO cliente (clinombre, cliapellido, clicorreo, clicontraseña, tipo_documento, numero_documento, departamento, edad, es_socio) "
                 + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/bd_peliculas", "root", "Katiaalfa*2024");
         PreparedStatement stmt = connection.prepareStatement(query)) {
        
        // Configurar los parámetros del PreparedStatement
        stmt.setString(1, nombre);
        stmt.setString(2, apellidos);
        stmt.setString(3, correo);
        stmt.setString(4, contraseña);
        stmt.setString(5, tipoDocumento);
        stmt.setString(6, numeroDocumento);
        stmt.setString(7, departamento);
        stmt.setInt(8, edad);
        stmt.setBoolean(9, true); // Es socio (TRUE)

        // Ejecutar la consulta
        int filasAfectadas = stmt.executeUpdate();
        if (filasAfectadas > 0) {
            JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos(); // Método opcional para limpiar los campos
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar al cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_panelRound5MouseClicked

    // PARA LIMPIAR 
    private void limpiarCampos() {
    txtNombre.setText("");
    txtApellidos.setText("");
    txtCorreo.setText("");
    txtContraeña.setText("");
    txtDepartamento.setText("");
    txtNumeroDocumento.setText("");
    txtEdad.setText("");
    cbxTipoDocumento.setSelectedIndex(0); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private redondeadoPanel.PanelRound panelRound5;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContraeña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroDocumento;
    // End of variables declaration//GEN-END:variables
    
    

}
