package presentacion;

import fuentes.Fuentes;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.border.LineBorder;

public class PanelProximosEstrenos extends javax.swing.JPanel {

    private int idPelicula;
    private int idCliente;
    
    Fuentes tipoFuente= new Fuentes();
    public PanelProximosEstrenos() {
        initComponents();
    }
    
    public PanelProximosEstrenos(int idCliente) {
        this.idCliente = idCliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lbl_hasta_UH = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_Avengers = new javax.swing.JLabel();
        lbl_Spiderman = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_Sonic3 = new javax.swing.JLabel();
        lbl_El_tiempo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_Mufasa = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnComprar1 = new javax.swing.JButton();
        btnDetalles1 = new javax.swing.JButton();
        btnComprar2 = new javax.swing.JButton();
        btnDetalles2 = new javax.swing.JButton();
        btnComprar3 = new javax.swing.JButton();
        btnDetalles3 = new javax.swing.JButton();
        btnComprar5 = new javax.swing.JButton();
        btnDetalles5 = new javax.swing.JButton();
        btnComprar4 = new javax.swing.JButton();
        btnComprar6 = new javax.swing.JButton();
        btnDetalles4 = new javax.swing.JButton();
        btnDetalles6 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(674, 611));

        jLabel4.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Animacion, 2h, APT");

        lbl_hasta_UH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hasta el ultimo hombre.jpg"))); // NOI18N
        lbl_hasta_UH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Avengers: Endgame");

        jLabel15.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Spiderman");

        jLabel7.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Accion, 3h, APT");

        jLabel16.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Acción, 2h 5 min, +14");

        lbl_Avengers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Los Vengadores.jpg"))); // NOI18N
        lbl_Avengers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lbl_Spiderman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Spiderman.jpg"))); // NOI18N
        lbl_Spiderman.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel8.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("El tiempo que tenemos");

        lbl_Sonic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sonic 3.jpg"))); // NOI18N
        lbl_Sonic3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lbl_El_tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/El tiempo que tenemos.jpg"))); // NOI18N
        lbl_El_tiempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel12.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sonic 3");

        jLabel11.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Animacion, 1h 40 min, APT");

        lbl_Mufasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mufasa.jpg"))); // NOI18N
        lbl_Mufasa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel13.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hasta el ultimo hombre");

        jLabel1.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mufasa");

        jLabel14.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Drama, 1h 50 min, +18");

        jLabel9.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Drama, 1h 44min, +14");

        btnComprar1.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar1.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar1.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar1.setText("Comprar");
        btnComprar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar1MouseExited(evt);
            }
        });
        btnComprar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar1ActionPerformed(evt);
            }
        });

        btnDetalles1.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles1.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles1.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles1.setText("Ver detalles");
        btnDetalles1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles1MouseExited(evt);
            }
        });
        btnDetalles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles1ActionPerformed(evt);
            }
        });

        btnComprar2.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar2.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar2.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar2.setText("Comprar");
        btnComprar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar2MouseExited(evt);
            }
        });
        btnComprar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar2ActionPerformed(evt);
            }
        });

        btnDetalles2.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles2.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles2.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles2.setText("Ver detalles");
        btnDetalles2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles2MouseExited(evt);
            }
        });
        btnDetalles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles2ActionPerformed(evt);
            }
        });

        btnComprar3.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar3.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar3.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar3.setText("Comprar");
        btnComprar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar3MouseExited(evt);
            }
        });
        btnComprar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar3ActionPerformed(evt);
            }
        });

        btnDetalles3.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles3.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles3.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles3.setText("Ver detalles");
        btnDetalles3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles3MouseExited(evt);
            }
        });
        btnDetalles3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles3ActionPerformed(evt);
            }
        });

        btnComprar5.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar5.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar5.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar5.setText("Comprar");
        btnComprar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar5MouseExited(evt);
            }
        });
        btnComprar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar5ActionPerformed(evt);
            }
        });

        btnDetalles5.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles5.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles5.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles5.setText("Ver detalles");
        btnDetalles5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles5MouseExited(evt);
            }
        });
        btnDetalles5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles5ActionPerformed(evt);
            }
        });

        btnComprar4.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar4.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar4.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar4.setText("Comprar");
        btnComprar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar4MouseExited(evt);
            }
        });
        btnComprar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar4ActionPerformed(evt);
            }
        });

        btnComprar6.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar6.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar6.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar6.setText("Comprar");
        btnComprar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar6MouseExited(evt);
            }
        });
        btnComprar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar6ActionPerformed(evt);
            }
        });

        btnDetalles4.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles4.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles4.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles4.setText("Ver detalles");
        btnDetalles4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles4MouseExited(evt);
            }
        });
        btnDetalles4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles4ActionPerformed(evt);
            }
        });

        btnDetalles6.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles6.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles6.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles6.setText("Ver detalles");
        btnDetalles6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles6MouseExited(evt);
            }
        });
        btnDetalles6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Mufasa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Avengers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_El_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnComprar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalles1)
                        .addGap(30, 30, 30)
                        .addComponent(btnComprar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalles2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnComprar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalles3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComprar4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetalles4)
                                .addGap(24, 24, 24)
                                .addComponent(btnComprar5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetalles5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_Sonic3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(lbl_hasta_UH, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14)
                                                .addGap(14, 14, 14)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnComprar6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDetalles6))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Spiderman))
                                    .addGap(27, 27, 27)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Mufasa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_El_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_Avengers, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles1)
                        .addComponent(btnComprar1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles2)
                        .addComponent(btnComprar2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles3)
                        .addComponent(btnComprar3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Spiderman, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Sonic3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_hasta_UH, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles5)
                        .addComponent(btnComprar5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles6)
                        .addComponent(btnComprar6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles4)
                        .addComponent(btnComprar4)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar1MouseEntered
        btnComprar1.setBackground(new Color(153,0,51));
    }//GEN-LAST:event_btnComprar1MouseEntered

    private void btnComprar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar1MouseExited
        btnComprar1.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar1MouseExited

    private void btnDetalles1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles1MouseEntered
        btnDetalles1.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_btnDetalles1MouseEntered

    private void btnDetalles1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles1MouseExited
        btnDetalles1.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles1MouseExited

    private void btnComprar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar2MouseEntered
        btnComprar2.setBackground(new Color(153,0,51));
    }//GEN-LAST:event_btnComprar2MouseEntered

    private void btnComprar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar2MouseExited
        btnComprar2.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar2MouseExited

    private void btnDetalles2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles2MouseEntered
        btnDetalles2.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_btnDetalles2MouseEntered

    private void btnDetalles2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles2MouseExited
        btnDetalles2.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles2MouseExited

    private void btnComprar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar3MouseEntered
        btnComprar3.setBackground(new Color(153,0,51));
    }//GEN-LAST:event_btnComprar3MouseEntered

    private void btnComprar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar3MouseExited
        btnComprar3.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar3MouseExited

    private void btnDetalles3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles3MouseEntered
        btnDetalles3.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_btnDetalles3MouseEntered

    private void btnDetalles3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles3MouseExited
        btnDetalles3.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles3MouseExited

    private void btnComprar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar4MouseEntered
        btnComprar4.setBackground(new Color(153,0,51));
    }//GEN-LAST:event_btnComprar4MouseEntered

    private void btnComprar4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar4MouseExited
        btnComprar4.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar4MouseExited

    private void btnDetalles4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles4MouseEntered
        btnDetalles4.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_btnDetalles4MouseEntered

    private void btnDetalles4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles4MouseExited
        btnDetalles4.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles4MouseExited

    private void btnComprar5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar5MouseEntered
        btnComprar5.setBackground(new Color(153,0,51));
    }//GEN-LAST:event_btnComprar5MouseEntered

    private void btnComprar5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar5MouseExited
        btnComprar5.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar5MouseExited

    private void btnDetalles5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles5MouseEntered
        btnDetalles5.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_btnDetalles5MouseEntered

    private void btnDetalles5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles5MouseExited
        btnDetalles5.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles5MouseExited

    private void btnComprar6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar6MouseEntered
        btnComprar6.setBackground(new Color(153,0,51));
    }//GEN-LAST:event_btnComprar6MouseEntered

    private void btnComprar6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar6MouseExited
        btnComprar6.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar6MouseExited

    private void btnDetalles6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles6MouseEntered
        btnDetalles6.setBackground(new Color(0,51,51));
    }//GEN-LAST:event_btnDetalles6MouseEntered

    private void btnDetalles6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles6MouseExited
        btnDetalles6.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles6MouseExited

    private void btnComprar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar1ActionPerformed
        idPelicula=7;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar1ActionPerformed

    private void btnDetalles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles1ActionPerformed

    private void btnComprar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar2ActionPerformed
        idPelicula=8;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar2ActionPerformed

    private void btnDetalles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles2ActionPerformed

    private void btnComprar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar3ActionPerformed
        idPelicula=9;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar3ActionPerformed

    private void btnDetalles3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles3ActionPerformed

    private void btnComprar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar4ActionPerformed
        idPelicula=10;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar4ActionPerformed

    private void btnDetalles4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles4ActionPerformed

    private void btnComprar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar5ActionPerformed
        idPelicula=11;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar5ActionPerformed

    private void btnDetalles5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles5ActionPerformed

    private void btnComprar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar6ActionPerformed
        idPelicula=12;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar6ActionPerformed

    private void btnDetalles6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles6ActionPerformed


        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar1;
    private javax.swing.JButton btnComprar2;
    private javax.swing.JButton btnComprar3;
    private javax.swing.JButton btnComprar4;
    private javax.swing.JButton btnComprar5;
    private javax.swing.JButton btnComprar6;
    private javax.swing.JButton btnDetalles1;
    private javax.swing.JButton btnDetalles2;
    private javax.swing.JButton btnDetalles3;
    private javax.swing.JButton btnDetalles4;
    private javax.swing.JButton btnDetalles5;
    private javax.swing.JButton btnDetalles6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_Avengers;
    private javax.swing.JLabel lbl_El_tiempo;
    private javax.swing.JLabel lbl_Mufasa;
    private javax.swing.JLabel lbl_Sonic3;
    private javax.swing.JLabel lbl_Spiderman;
    private javax.swing.JLabel lbl_hasta_UH;
    // End of variables declaration//GEN-END:variables
    
}
