package presentacion;

import entidades.Cliente;
import entidades.PilaCliente;
import java.sql.*;
import fuentes.Fuentes;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JFrame;
import javax.swing.border.LineBorder;
import javax.swing.*;

public class PanelPagoBilleteras extends javax.swing.JPanel {

    private int idCliente;
    private int idVenta;

    Fuentes tipoFuente = new Fuentes();

    public PanelPagoBilleteras(int idCliente, int idVenta) {
//        JOptionPane.showMessageDialog(null, "IDCLIENTE: "+idCliente);
//        JOptionPane.showMessageDialog(null, "IDVENTA: "+idVenta);
        this.idCliente = idCliente;
        this.idVenta = idVenta;
        initComponents();
    }

    public PanelPagoBilleteras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNroCelular = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        panelRound1 = new redondeadoPanel.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        txtNroDocumento = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblYape = new javax.swing.JLabel();
        lblPlin = new javax.swing.JLabel();
        lblTunki = new javax.swing.JLabel();
        cbxDocumento = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnYape = new javax.swing.JButton();
        btnPlin = new javax.swing.JButton();
        btnTunki = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel1.setText("Número de Celular");

        txtNroCelular.setForeground(new java.awt.Color(204, 204, 204));
        txtNroCelular.setText("Número de Celular");
        txtNroCelular.setBorder(null);
        txtNroCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNroCelularMousePressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        panelRound1.setBackground(new java.awt.Color(0, 51, 153));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRound1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRound1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound1MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAGAR");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(16, 16, 16))
        );

        txtNroDocumento.setForeground(new java.awt.Color(204, 204, 204));
        txtNroDocumento.setText("Número de documento");
        txtNroDocumento.setBorder(null);
        txtNroDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNroDocumentoMousePressed(evt);
            }
        });
        txtNroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroDocumentoActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel5.setText("Número de documento:");

        jLabel4.setFont(new java.awt.Font("Square721 BT", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Tarjeta de crédito o débito");

        lblYape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yape.png"))); // NOI18N
        lblYape.setPreferredSize(new java.awt.Dimension(61, 31));

        lblPlin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plin.png"))); // NOI18N

        lblTunki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tunki.png"))); // NOI18N

        cbxDocumento.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        cbxDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Carnet de extranjería", "Pasaporte", "Rut" }));

        jLabel9.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel9.setText("Tipo de Documento:");

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel10.setText("*No se hacen cambios ni devoluciones");

        jLabel11.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        jLabel11.setText("*Toda la información de pago es segura");

        jLabel6.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel6.setText("Elige alguna de las opciones de pago:");

        btnYape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yape boton.png"))); // NOI18N
        btnYape.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        btnYape.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnYapeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnYapeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnYapeMouseExited(evt);
            }
        });
        btnYape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYapeActionPerformed(evt);
            }
        });

        btnPlin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plin boton.jpg"))); // NOI18N
        btnPlin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        btnPlin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlinMouseExited(evt);
            }
        });

        btnTunki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tunki boton.png"))); // NOI18N
        btnTunki.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        btnTunki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTunkiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTunkiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTunkiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1)
                                        .addComponent(jLabel1)
                                        .addComponent(txtNroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(55, 55, 55))
                                    .addComponent(txtNroDocumento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblYape, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblPlin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblTunki, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 54, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnYape, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnPlin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnTunki, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTunki, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYape, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYape, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTunki, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void txtNroCelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNroCelularMousePressed
        if (txtNroCelular.getText().equals("Número de Celular")) {
            txtNroCelular.setText("");
            txtNroCelular.setForeground(Color.black);
        }

        if (txtNroDocumento.getText().equals("")) {
            txtNroDocumento.setText("Número de documento");
            txtNroDocumento.setForeground(Color.decode("#CCCCCC"));
        }
    }//GEN-LAST:event_txtNroCelularMousePressed

    private void panelRound1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound1MouseEntered
        panelRound1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        panelRound1.setBackground(Color.red);
    }//GEN-LAST:event_panelRound1MouseEntered

    private void txtNroDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNroDocumentoMousePressed
        if (txtNroCelular.getText().equals("")) {
            txtNroCelular.setText("Número de Celular");
            txtNroCelular.setForeground(Color.decode("#CCCCCC"));
        }

        if (txtNroDocumento.getText().equals("Número de documento")) {
            txtNroDocumento.setText("");
            txtNroDocumento.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNroDocumentoMousePressed

    private void btnYapeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYapeMouseEntered
        btnYape.setBorder(new LineBorder(new Color(0, 51, 153), 3));
    }//GEN-LAST:event_btnYapeMouseEntered

    private void btnYapeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYapeMouseExited
        btnYape.setBorder(new LineBorder(Color.LIGHT_GRAY, 2));
    }//GEN-LAST:event_btnYapeMouseExited

    private void btnPlinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlinMouseEntered
        btnPlin.setBorder(new LineBorder(new Color(0, 51, 153), 3));
    }//GEN-LAST:event_btnPlinMouseEntered

    private void btnPlinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlinMouseExited
        btnPlin.setBorder(new LineBorder(Color.LIGHT_GRAY, 2));
    }//GEN-LAST:event_btnPlinMouseExited

    private void btnTunkiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTunkiMouseEntered
        btnTunki.setBorder(new LineBorder(new Color(0, 51, 153), 3));
    }//GEN-LAST:event_btnTunkiMouseEntered

    private void btnTunkiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTunkiMouseExited
        btnTunki.setBorder(new LineBorder(Color.LIGHT_GRAY, 2));
    }//GEN-LAST:event_btnTunkiMouseExited

    private void panelRound1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound1MouseExited
        panelRound1.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_panelRound1MouseExited

    private void btnYapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYapeActionPerformed

    private void txtNroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroDocumentoActionPerformed

    private void panelRound1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound1MousePressed
        // TODO add your handling code here:
        try {
            // Crear la conexión a la base de datos
            Connection connection = null;
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bd_peliculas", "root", "Hernan77..");

                // Crear una instancia de la pila de clientes y cargarla con los datos existentes
                PilaCliente pilaClientes = new PilaCliente();
                cargarClientesEnPila(pilaClientes, connection); // Método actualizado que utiliza la conexión
                Cliente cliente = pilaClientes.buscarPorId(idCliente);
//                System.out.println("Cliente encontrado: " + (cliente != null ? cliente.getNombre() : "null"));

                // Verificar si el cliente es registrado o no
                if (idCliente == -1 || idCliente == 0) {
                    JOptionPane.showMessageDialog(null, "Cliente no registrado. Complete los datos manualmente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                    // Dejar el campo de celular libre para que lo llenen manualmente
                    txtNroCelular.setText("");
                } else {
                    // Rellenar automáticamente los datos del cliente
                    if (cliente != null) {
                        String tipoDocumento = cliente.getTipoDocumento();
                        cbxDocumento.setSelectedItem(tipoDocumento);
                        txtNroDocumento.setText(cliente.getNumeroDocumento());
                        
                        cbxDocumento.setEnabled(true);
                        txtNroDocumento.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "El cliente no existe en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }

                // Actualizar la venta con los datos del cliente
                actualizarVentaConCliente(connection, idVenta, idCliente, (String) cbxDocumento.getSelectedItem(), txtNroDocumento.getText());

                // Registrar el método de pago en la base de datos
                String numeroCelular = txtNroCelular.getText();
                actualizarVentaConPago(connection, idVenta, "billetera", null, null, null, numeroCelular);

                // Mensaje de confirmación
                JOptionPane.showMessageDialog(null, "Pago registrado con billetera.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Cerrar la pestaña actual y regresar a FrmPrincipal
                JFrame frameContenedor = (JFrame) SwingUtilities.getWindowAncestor(this); // Obtiene el JFrame padre
                frameContenedor.dispose();
                FrmPRINCIPAL f = new FrmPRINCIPAL(idCliente, cliente.getNombre(), cliente.getApellido());
                f.setVisible(true);

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error en la conexión a la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                if (connection != null) {
                    try {
                        connection.close(); // Cerrar la conexión
                    } catch (SQLException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al registrar el pago con billetera.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_panelRound1MousePressed

    private void btnYapeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYapeMouseClicked
        btnYape.setBorder(new LineBorder(new Color(0, 51, 153), 3));
    }//GEN-LAST:event_btnYapeMouseClicked

    private void btnPlinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlinMouseClicked
        btnPlin.setBorder(new LineBorder(new Color(0, 51, 153), 3));
    }//GEN-LAST:event_btnPlinMouseClicked

    private void btnTunkiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTunkiMouseClicked
        btnTunki.setBorder(new LineBorder(new Color(0, 51, 153), 3));
    }//GEN-LAST:event_btnTunkiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlin;
    private javax.swing.JButton btnTunki;
    private javax.swing.JButton btnYape;
    private javax.swing.JComboBox<String> cbxDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblPlin;
    private javax.swing.JLabel lblTunki;
    private javax.swing.JLabel lblYape;
    private redondeadoPanel.PanelRound panelRound1;
    private javax.swing.JTextField txtNroCelular;
    private javax.swing.JTextField txtNroDocumento;
    // End of variables declaration//GEN-END:variables

    private static void actualizarVentaConCliente(Connection connection, int idVenta, int idCliente, String tipoDocumento, String numeroDocumento) throws SQLException {
        String query = "UPDATE venta SET idcliente = ?, tipo_documento = ?, numero_documento = ? WHERE idventa = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setObject(1, idCliente > 0 ? idCliente : null);
            statement.setString(2, tipoDocumento);
            statement.setString(3, numeroDocumento);
            statement.setInt(4, idVenta);
            statement.executeUpdate();
        }
    }

    private static void actualizarVentaConPago(Connection connection, int idVenta, String metodoPago, String numeroTarjeta, String cvv, String fechaVencimiento, String numeroCelular) throws SQLException {
        String query = "UPDATE venta SET metodopago = ?, numero_tarjeta = ?, cvv = ?, fecha_vencimiento = ?, numero_celular = ? WHERE idventa = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, metodoPago);
            statement.setString(2, numeroTarjeta);
            statement.setString(3, cvv);
            statement.setString(4, fechaVencimiento);
            statement.setString(5, numeroCelular);
            statement.setInt(6, idVenta);
            statement.executeUpdate();
        }
    }

    private static String obtenerTipoDocumentoCliente(Connection connection, String numeroDocumento) throws SQLException {
        String query = "SELECT tipo_documento FROM cliente WHERE numero_documento = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, numeroDocumento);
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                return resultSet.getString("tipo_documento");
            }
        }
        return "N/T";
    }

    private static String obtenerNombreCliente(Connection connection, String numeroDocumento) throws SQLException {
        String query = "SELECT tipo_documento FROM cliente WHERE numero_documento = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, numeroDocumento);
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                return resultSet.getString("tipo_documento");
            }
        }
        return "N/T";
    }

    private static String obtenerApellidoCliente(Connection connection, String numeroDocumento) throws SQLException {
        String query = "SELECT tipo_documento FROM cliente WHERE numero_documento = ?";
        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, numeroDocumento);
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                return resultSet.getString("tipo_documento");
            }
        }
        return "N/T";
    }

    public void cargarClientesEnPila(PilaCliente pila, Connection connection) {
        String query = "SELECT * FROM cliente"; // Cambia el nombre de la tabla según tu base de datos
        try (PreparedStatement stmt = connection.prepareStatement(query); ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) {
                Cliente cliente = new Cliente(
                        rs.getInt("idcliente"),
                        rs.getString("clinombre"),
                        rs.getString("cliapellido"),
                        rs.getInt("edad"),
                        rs.getString("clicorreo"),
                        rs.getString("clicontraseña"),
                        rs.getString("tipo_documento"),
                        rs.getString("numero_documento"),
                        rs.getString("departamento"),
                        rs.getBoolean("es_socio")
                );
                pila.push(cliente); // Agrega el cliente a la pila
            }
            System.out.println("Clientes cargados en la pila exitosamente.");
        } catch (SQLException e) {
            System.err.println("Error al cargar los clientes: " + e.getMessage());
        }
    }

}
