/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author HP
 */
public class PanelMAS18 extends javax.swing.JPanel {

    /**
     * Creates new form PanelMAS18
     */
    public PanelMAS18() {
     initComponents();

        setLayout(new FlowLayout(FlowLayout.LEFT, 70, 70));  // Elementos en una fila con espacio de 20px
        setBackground(Color.WHITE); // Fondo blanco

        // Crear y agregar la película 1
        add(createMoviePanel("Joker", "src/imagenes/Joker.jpg"));
        add(createMoviePanel("Hasta el ultimo hombre", "src/imagenes/Hasta el ultimo hombre.jpg"));
        

        // Crear y agregar la película 2
       
        
        
        
        // Crear los botones para las películas
        JButton btnComprar1 = new JButton("Comprar");
        JButton btnDetalles1 = new JButton("Detalles");

        // Añadir los botones a las acciones correspondientes
        btnComprar1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                FrmComprar frmComprar = new FrmComprar();
                frmComprar.setVisible(true);
            }
        });

        btnDetalles1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                FrmDetallePelicula detallePelicula = new FrmDetallePelicula();
                detallePelicula.setVisible(true);
            }
        });
    }

    private JPanel createMoviePanel(String movieTitle, String imagePath) {
    JPanel moviePanel = new JPanel();
    moviePanel.setLayout(new BorderLayout());
    // Quitar o hacer invisible el borde
    moviePanel.setBorder(BorderFactory.createLineBorder(Color.WHITE)); // Borde blanco (invisible en fondo blanco)
    moviePanel.setBackground(Color.WHITE); // Fondo blanco para el panel de cada película

    // Crear el JLabel de la imagen
    JLabel lblImage = new JLabel(new ImageIcon(imagePath));
    lblImage.setHorizontalAlignment(SwingConstants.CENTER);

    // Crear el JLabel del título (debajo de la imagen)
    JLabel lblTitle = new JLabel(movieTitle, SwingConstants.CENTER);
    lblTitle.setOpaque(true); // Hacer que el fondo sea visible
    lblTitle.setBackground(Color.WHITE); // Fondo blanco
    lblTitle.setForeground(new Color(0, 0, 0)); // Texto negro
    lblTitle.setFont(new Font("Square721 BT", Font.BOLD, 12));

    // Crear los botones
    JPanel buttonPanel = new JPanel();
    buttonPanel.setLayout(new FlowLayout());
    buttonPanel.setBackground(Color.WHITE); // Fondo blanco para el panel de botones

    // Botón "Comprar"
    JButton btnBuy = new JButton("Comprar");
    btnBuy.setBackground(new Color(255, 51, 51)); // Fondo rojo
    btnBuy.setForeground(new Color(255, 255, 255)); // Texto blanco
    btnBuy.setFont(new Font("Square721 BT", Font.BOLD, 12));

    // Botón "Ver Detalles"
    JButton btnDetails = new JButton("Ver Detalles");
    btnDetails.setBackground(new Color(0, 51, 153)); // Fondo azul oscuro
    btnDetails.setForeground(new Color(255, 255, 255)); // Texto blanco
    btnDetails.setFont(new Font("Square721 BT", Font.BOLD, 12));

    // Agregar botones al panel de botones
    buttonPanel.add(btnBuy);
    buttonPanel.add(btnDetails);

    // Agregar componentes al panel de la película
    moviePanel.add(lblImage, BorderLayout.NORTH); // Imagen en la parte superior
    moviePanel.add(lblTitle, BorderLayout.CENTER); // Título debajo de la imagen
    moviePanel.add(buttonPanel, BorderLayout.SOUTH); // Botones al final

    return moviePanel;
    }
    public static void main(String[] args) {
        JFrame frame = new JFrame("Películas para Mayores de Edad");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(674, 640);

        PanelMAS18 panelAnimacion = new PanelMAS18();
        frame.add(panelAnimacion);

        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
