/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class PanelCarrusel extends javax.swing.JPanel {

    
    //IMAGENES DE PRUEBA
    private Icon imagen1= new ImageIcon(new ImageIcon(getClass().getResource("/imagenes/joker_wallpaper_final.jpg")).getImage().getScaledInstance(1107,653,0));
    private Icon imagen2= new ImageIcon(new ImageIcon(getClass().getResource("/imagenes/drstrange_wallpaper_final.jpg")).getImage().getScaledInstance(1107,653,0));
    private Icon imagen3= new ImageIcon(new ImageIcon(getClass().getResource("/imagenes/batman_wallpaper_final.jpg")).getImage().getScaledInstance(1107,653,0));
    
    private JLabel jLabel1= new JLabel(imagen1);
    private JLabel jLabel2= new JLabel(imagen2); 
    private JLabel jLabel3= new JLabel(imagen3);
    
    private int desplazamiento = 0;
    private boolean haciaLaIzquierda = true;
    private int velocidad = 8;
    private int velocidadMaxima = 12;
    private int velocidadMinima = 6; 
    private int desaceleracion = 1; 
    private int umbralDesaceleracion = 1000;
    private int pausa = 4000;
    
    public PanelCarrusel() {
        initComponents();
        //AGREGAR LOS 3 AL MISMO TIEMPO
        jLabel1.setIcon(imagen1);       
        jLabel2.setIcon(imagen2);
        jLabel3.setIcon(imagen3);
        jLabel1.setBounds(0, 0, 1107,653);
        jLabel2.setBounds(1107, 0, 1107,653);
        jLabel3.setBounds(2214, 0, 1107,653);
        this.add(jLabel1);
        this.add(jLabel2);
        this.add(jLabel3);
        moverImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1107, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    
    
    private void moverImagenes() {
        Timer[] temporizadores = new Timer[2]; 
        temporizadores[0] = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (haciaLaIzquierda) {
                    if (desplazamiento >= umbralDesaceleracion) {
                        if (velocidad > velocidadMinima) {
                            velocidad -= desaceleracion;
                        }
                    } else if (velocidad < velocidadMaxima) {
                        velocidad += 1;
                    }
                    desplazamiento += velocidad;
                    jLabel1.setBounds(-desplazamiento, 0, 1107, 653);
                    jLabel2.setBounds(1107 - desplazamiento, 0, 1107, 653);
                    jLabel3.setBounds(1107 * 2 - desplazamiento, 0, 1107, 653);
                    if (desplazamiento >= 1107) { 
                        JLabel temp = jLabel1;
                        jLabel1 = jLabel2;
                        jLabel2 = jLabel3;
                        jLabel3 = temp;

                        jLabel1.setBounds(0, 0, 1107, 653);
                        jLabel2.setBounds(1107, 0, 1107, 653);
                        jLabel3.setBounds(1107 * 2, 0, 1107, 653);
                        desplazamiento = 0;

                        temporizadores[0].stop();
                        temporizadores[1].start();
                    }
                }
            }
        });
        temporizadores[1] = new Timer(pausa, new ActionListener() {
            @Override   
            public void actionPerformed(ActionEvent e) {
                temporizadores[1].stop();
                temporizadores[0].start();
            }
        });
        temporizadores[1].start();
    }
    
}
