package presentacion;

import fuentes.Fuentes;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.border.LineBorder;

public class PanelCartelera extends javax.swing.JPanel {

    private String titulo;
    private String genero;
    private String censura;
    private String duracion;
    
    private int idCliente;
    
    private int idPelicula;

    Fuentes tipoFuente = new Fuentes();

    public PanelCartelera() {
        initComponents();
    }
    
    public PanelCartelera(int idCliente) {
        this.idCliente = idCliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelText = new javax.swing.JLabel();
        lbl_Doctor_Strange = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelText2 = new javax.swing.JLabel();
        labelText6 = new javax.swing.JLabel();
        lbl_Titanic = new javax.swing.JLabel();
        lbl_Batman = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_Moana = new javax.swing.JLabel();
        lbl_Joker = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelText4 = new javax.swing.JLabel();
        lbl_Los_Increibles = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelText5 = new javax.swing.JLabel();
        labelText3 = new javax.swing.JLabel();
        btnComprar1 = new javax.swing.JButton();
        btnDetalles1 = new javax.swing.JButton();
        btnComprar2 = new javax.swing.JButton();
        btnDetalles2 = new javax.swing.JButton();
        btnComprar3 = new javax.swing.JButton();
        btnDetalles3 = new javax.swing.JButton();
        btnComprar5 = new javax.swing.JButton();
        btnDetalles5 = new javax.swing.JButton();
        btnComprar4 = new javax.swing.JButton();
        btnComprar6 = new javax.swing.JButton();
        btnDetalles4 = new javax.swing.JButton();
        btnDetalles6 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(674, 611));

        labelText.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        labelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelText.setText("Animación, 1h 40 min, APT");

        lbl_Doctor_Strange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Doctor Strange.jpg"))); // NOI18N
        lbl_Doctor_Strange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Titanic");

        jLabel15.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Batman");

        labelText2.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        labelText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelText2.setText("Drama, 3h 15min, +14");

        labelText6.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        labelText6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelText6.setText("Acción, 2h 5 min, +18");

        lbl_Titanic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Titanic.jpg"))); // NOI18N
        lbl_Titanic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lbl_Batman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Batman.jpg"))); // NOI18N
        lbl_Batman.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel8.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Joker");

        lbl_Moana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moana.jpg"))); // NOI18N
        lbl_Moana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lbl_Joker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Joker.jpg"))); // NOI18N
        lbl_Joker.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel12.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Moana");

        labelText4.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        labelText4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelText4.setText("Animación, 1h 40 min, APT");

        lbl_Los_Increibles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Los increibles.jpg"))); // NOI18N
        lbl_Los_Increibles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel13.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Doctor Strange");

        jLabel1.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Los Increíbles");

        labelText5.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        labelText5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelText5.setText("Accion, 1h 45min, +14");

        labelText3.setFont(new java.awt.Font("Square721 BT", 0, 10)); // NOI18N
        labelText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelText3.setText("Drama, 2h 15 min, +18");

        btnComprar1.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar1.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar1.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar1.setText("Comprar");
        btnComprar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar1MouseExited(evt);
            }
        });
        btnComprar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar1ActionPerformed(evt);
            }
        });

        btnDetalles1.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles1.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles1.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles1.setText("Ver detalles");
        btnDetalles1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles1MouseExited(evt);
            }
        });
        btnDetalles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles1ActionPerformed(evt);
            }
        });

        btnComprar2.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar2.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar2.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar2.setText("Comprar");
        btnComprar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar2MouseExited(evt);
            }
        });
        btnComprar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar2ActionPerformed(evt);
            }
        });

        btnDetalles2.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles2.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles2.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles2.setText("Ver detalles");
        btnDetalles2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles2MouseExited(evt);
            }
        });
        btnDetalles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles2ActionPerformed(evt);
            }
        });

        btnComprar3.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar3.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar3.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar3.setText("Comprar");
        btnComprar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar3MouseExited(evt);
            }
        });
        btnComprar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar3ActionPerformed(evt);
            }
        });

        btnDetalles3.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles3.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles3.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles3.setText("Ver detalles");
        btnDetalles3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles3MouseExited(evt);
            }
        });
        btnDetalles3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles3ActionPerformed(evt);
            }
        });

        btnComprar5.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar5.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar5.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar5.setText("Comprar");
        btnComprar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar5MouseExited(evt);
            }
        });
        btnComprar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar5ActionPerformed(evt);
            }
        });

        btnDetalles5.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles5.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles5.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles5.setText("Ver detalles");
        btnDetalles5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles5MouseExited(evt);
            }
        });
        btnDetalles5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles5ActionPerformed(evt);
            }
        });

        btnComprar4.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar4.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar4.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar4.setText("Comprar");
        btnComprar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar4MouseExited(evt);
            }
        });
        btnComprar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar4ActionPerformed(evt);
            }
        });

        btnComprar6.setBackground(new java.awt.Color(255, 51, 51));
        btnComprar6.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnComprar6.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar6.setText("Comprar");
        btnComprar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprar6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprar6MouseExited(evt);
            }
        });
        btnComprar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar6ActionPerformed(evt);
            }
        });

        btnDetalles4.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles4.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles4.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles4.setText("Ver detalles");
        btnDetalles4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles4MouseExited(evt);
            }
        });
        btnDetalles4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles4ActionPerformed(evt);
            }
        });

        btnDetalles6.setBackground(new java.awt.Color(0, 51, 153));
        btnDetalles6.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        btnDetalles6.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalles6.setText("Ver detalles");
        btnDetalles6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDetalles6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDetalles6MouseExited(evt);
            }
        });
        btnDetalles6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalles6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Los_Increibles, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelText2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Titanic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelText3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Joker, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelText4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Moana, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel13))
                            .addComponent(labelText5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbl_Doctor_Strange, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_Batman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelText6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComprar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetalles1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComprar4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetalles4)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComprar5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetalles5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprar6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetalles6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComprar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetalles2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprar3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetalles3)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Los_Increibles, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Joker, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_Titanic, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelText3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelText2)))))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles1)
                        .addComponent(btnComprar1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles3)
                        .addComponent(btnComprar3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles2)
                        .addComponent(btnComprar2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Moana, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(2, 2, 2)
                        .addComponent(labelText4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Doctor_Strange, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(labelText5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Batman, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)
                        .addComponent(labelText6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles6)
                        .addComponent(btnComprar6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles4)
                        .addComponent(btnComprar4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetalles5)
                        .addComponent(btnComprar5)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar1MouseEntered
        btnComprar1.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_btnComprar1MouseEntered

    private void btnComprar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar1MouseExited
        btnComprar1.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar1MouseExited

    private void btnDetalles1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles1MouseEntered
        btnDetalles1.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_btnDetalles1MouseEntered

    private void btnDetalles1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles1MouseExited
        btnDetalles1.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles1MouseExited

    private void btnComprar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar2MouseEntered
        btnComprar2.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_btnComprar2MouseEntered

    private void btnComprar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar2MouseExited
        btnComprar2.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar2MouseExited

    private void btnDetalles2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles2MouseEntered
        btnDetalles2.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_btnDetalles2MouseEntered

    private void btnDetalles2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles2MouseExited
        btnDetalles2.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles2MouseExited

    private void btnComprar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar3MouseEntered
        btnComprar3.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_btnComprar3MouseEntered

    private void btnComprar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar3MouseExited
        btnComprar3.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar3MouseExited

    private void btnDetalles3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles3MouseEntered
        btnDetalles3.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_btnDetalles3MouseEntered

    private void btnDetalles3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles3MouseExited
        btnDetalles3.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles3MouseExited

    private void btnComprar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar4MouseEntered
        btnComprar4.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_btnComprar4MouseEntered

    private void btnComprar4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar4MouseExited
        btnComprar4.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar4MouseExited

    private void btnDetalles4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles4MouseEntered
        btnDetalles4.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_btnDetalles4MouseEntered

    private void btnDetalles4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles4MouseExited
        btnDetalles4.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles4MouseExited

    private void btnComprar5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar5MouseEntered
        btnComprar5.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_btnComprar5MouseEntered

    private void btnComprar5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar5MouseExited
        btnComprar5.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar5MouseExited

    private void btnDetalles5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles5MouseEntered
        btnDetalles5.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_btnDetalles5MouseEntered

    private void btnDetalles5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles5MouseExited
        btnDetalles5.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles5MouseExited

    private void btnComprar6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar6MouseEntered
        btnComprar6.setBackground(new Color(153, 0, 51));
    }//GEN-LAST:event_btnComprar6MouseEntered

    private void btnComprar6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprar6MouseExited
        btnComprar6.setBackground(Color.red);
    }//GEN-LAST:event_btnComprar6MouseExited

    private void btnDetalles6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles6MouseEntered
        btnDetalles6.setBackground(new Color(0, 51, 51));
    }//GEN-LAST:event_btnDetalles6MouseEntered

    private void btnDetalles6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetalles6MouseExited
        btnDetalles6.setBackground(new Color(0, 51, 153));
    }//GEN-LAST:event_btnDetalles6MouseExited

    private void btnComprar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar1ActionPerformed

        String[] partes = labelText.getText().split(", ");

        // Asignar cada parte a las variables correspondientes
        genero = partes[0];  // Primera parte: "Animación"
        duracion = partes[1];  // Segunda parte: "1h 40 min"
        censura = partes[2];  // Tercera parte: "APT"
        
        idPelicula=1;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar1ActionPerformed

    private void btnDetalles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles1ActionPerformed
        FrmDetallePelicula detallePelicula = new FrmDetallePelicula();
        detallePelicula.setVisible(true);
    }//GEN-LAST:event_btnDetalles1ActionPerformed

    private void btnComprar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar2ActionPerformed
        idPelicula=2;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar2ActionPerformed

    private void btnDetalles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles2ActionPerformed

    private void btnComprar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar3ActionPerformed
        idPelicula=3;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar3ActionPerformed

    private void btnDetalles3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles3ActionPerformed

    private void btnComprar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar4ActionPerformed
        idPelicula=4;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar4ActionPerformed

    private void btnDetalles4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles4ActionPerformed

    private void btnComprar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar5ActionPerformed
        idPelicula=5;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar5ActionPerformed

    private void btnDetalles5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles5ActionPerformed

    private void btnComprar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar6ActionPerformed
        idPelicula=6;

        FrmComprar frmComprar = new FrmComprar(idCliente, idPelicula);
        frmComprar.setVisible(true);
    }//GEN-LAST:event_btnComprar6ActionPerformed

    private void btnDetalles6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalles6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalles6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar1;
    private javax.swing.JButton btnComprar2;
    private javax.swing.JButton btnComprar3;
    private javax.swing.JButton btnComprar4;
    private javax.swing.JButton btnComprar5;
    private javax.swing.JButton btnComprar6;
    private javax.swing.JButton btnDetalles1;
    private javax.swing.JButton btnDetalles2;
    private javax.swing.JButton btnDetalles3;
    private javax.swing.JButton btnDetalles4;
    private javax.swing.JButton btnDetalles5;
    private javax.swing.JButton btnDetalles6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelText;
    private javax.swing.JLabel labelText2;
    private javax.swing.JLabel labelText3;
    private javax.swing.JLabel labelText4;
    private javax.swing.JLabel labelText5;
    private javax.swing.JLabel labelText6;
    private javax.swing.JLabel lbl_Batman;
    private javax.swing.JLabel lbl_Doctor_Strange;
    private javax.swing.JLabel lbl_Joker;
    private javax.swing.JLabel lbl_Los_Increibles;
    private javax.swing.JLabel lbl_Moana;
    private javax.swing.JLabel lbl_Titanic;
    // End of variables declaration//GEN-END:variables

}
